"""Application constants for Frank the Chatter bot"""

from datetime import timedelta

# Database Settings
MAX_DATABASE_SIZE_GB = 15.0
MAX_MESSAGES_PER_CHANNEL = 1000
DEFAULT_RECENT_MESSAGES = 100
MESSAGES_CLEANUP_MARGIN = 100
CLEANUP_CHANNEL_KEEP_LAST = 500
CLEANUP_DAYS_PRIMARY = 30
CLEANUP_DAYS_SECONDARY = 7
DB_SIZE_CHECK_INTERVAL = timedelta(hours=1)

# Conversion Constants
BYTES_PER_MB = 1024 * 1024
MB_PER_GB = 1024

# AI Context Settings
MAX_MESSAGE_CONTEXT_FOR_AI = 20

# AI Generation Settings
AI_DEFAULT_TEMPERATURE = 1.0
AI_TOP_P = 0.95
AI_TOP_K = 20
AI_MAX_IMAGE_UPLOAD = 10
AI_MAX_RESPONSE_CHARS = 2000
AI_RESPONSE_TRUNCATE_TO = 1997
AI_RANDOM_REPLY_MAX_TOKENS = 10000

# Command Settings
SUMMARIZE_MAX_COUNT = 500

# Logging Settings
LOG_FILE_MAX_BYTES = 10 * 1024 * 1024
LOG_FILE_BACKUP_COUNT = 5
LOG_MESSAGE_PREVIEW_LENGTH = 100
TOP_CHANNELS_TO_SHOW = 5
