name: Lint

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install ruff
        run: pip install ruff==0.6.9
      - name: Run ruff lint
        run: ruff check .
      - name: Run ruff format --check
        run: ruff format --check .
